import 'package:ai_task_manager/screens/employee_dashboard.dart';
import 'package:ai_task_manager/screens/login_screen.dart';
import 'package:ai_task_manager/screens/manager_dashboard.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This was generated by the CLI

void main() async {
  // 1. Ensure Flutter is ready
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Start Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'AI Task Manager',
      // Instead of LoginScreen(), we point to AuthWrapper
      home: const AuthWrapper(),
    );
  }
}

class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      // This stream listens to login/logout events automatically
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // 1. If Firebase is still checking the session
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            backgroundColor: Colors.black,
            body: Center(child: CircularProgressIndicator(color: Colors.blueAccent)),
          );
        }

        // 2. If the user is logged in
        if (snapshot.hasData) {
          return const RoleRedirector();
        }

        // 3. If no user is logged in
        return const LoginScreen();
      },
    );
  }
}

// This helper widget checks the Firestore role once the user is authenticated
class RoleRedirector extends StatelessWidget {
  const RoleRedirector({super.key});

  @override
  Widget build(BuildContext context) {
    final user = FirebaseAuth.instance.currentUser;

    return FutureBuilder<DocumentSnapshot>(
      future: FirebaseFirestore.instance.collection('users').doc(user?.uid).get(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            backgroundColor: Colors.black,
            body: Center(child: CircularProgressIndicator(color: Colors.blueAccent)),
          );
        }

        if (snapshot.hasData && snapshot.data!.exists) {
          String role = snapshot.data!['role'];
          return role == 'manager' ? const ManagerDashboard() : const EmployeeDashboard();
        }

        // Default back to login if something goes wrong
        return const LoginScreen();
      },
    );
  }
}


